# If not running interactively, don't do anything
[[ $- != *i* ]] && return

BLUE='\e[0;34m'
NOCOLOR='\e[m'
export PS1="${BLUE}[\u@\h: \W]\$ ${NOCOLOR}"

# Long persistent history
export HISTFILESIZE=100000
export HISTSIZE=100000
shopt -s histappend

# Combine multiline commands into one in history
shopt -s cmdhist

# Do not save consecutive duplicate commands or commands that start with a space
HISTCONTROL=ignoreboth

# Show files after changing directory.
cdls() {
    builtin cd "$@"
    ls
}
alias cd='cdls'

# Tab completion ignores case
bind 'set completion-ignore-case on'

# Search history with up and down arrows
bind '"\e[A":history-search-backward'
bind '"\e[B":history-search-forward'

# I use Vim
export EDITOR="vim"

# Setup ssh-agent
SSH_ENV="$HOME/.ssh/agent-environment"

function start_agent {
    ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    chmod 600 "${SSH_ENV}"
    . "${SSH_ENV}" > /dev/null
}

if [ -f "${SSH_ENV}" ]; then
    . "${SSH_ENV}" > /dev/null
    #ps ${SSH_AGENT_PID} doesn't work under cywgin
    ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
        start_agent;
    }
else
    start_agent;
fi
